---
title: Tomasz Okraska blog
timezone: Europe/Warsaw
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Tomasz Okraska
description: Everyday adventures with coding
avatar: 
footer-links:
  dribbble: 
  email: okraska.tomasz@gmail.com
  facebook: 
  flickr: 
  github: okraskat
  instagram: 
  linkedin: 
  pinterest: 
  rss: 
  twitter: tomasz_okraska
  stackoverflow: 
  youtube: 
  googleplus: 
disqus: okraskat-github-io
google_analytics: 
url: https://okraskat.github.io
baseurl: 
permalink: "/:title/"
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: expanded
gems:
- jekyll-sitemap
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
